# REDIS KEYS
SYNTHETIC_DATA_KEY = "SYNTHETIC_DATA"
SYNTHETIC_DATA_VERSIONS_KEY = "SYNTHETIC_DATA_VERSIONS"
SYNTHETIC_SCHEDULING_QUEUE_KEY = "SYNTHETIC_SCHEDULING_QUEUE"
CONTROL_NODE_QUEUE_KEY = "CONTROL_NODE_QUEUE_KEY"
PUBLIC_KEYPAIR_INFO_KEY = "PUBLIC_KEYPAIR_INFO"
QUERY_QUEUE_KEY = "QUERY_QUEUE"
QUERY_RESULTS_KEY = "QUERY_RESULTS"
HOTKEY_INFO_KEY = "HOTKEY_INFO"
CAPACITIES_KEY = "CAPACITIES"
CONTENDER_IDS_KEY = "CONTENDER_IDS"
PARITICIPANT_IDS_TO_STOP_KEY = "PARITICIPANT_IDS_TO_STOP"
WEIGHTS_TO_SET_QUEUE_KEY = "WEIGHTS_TO_SET_QUEUE"
CONTROL_TASK_CHUNK_SIZE = 10


# Signing service stuff
SIGNING_DENDRITE_QUEUE_KEY = "SIGNING_DENDRITE_QUEUE"
SIGNING_WEIGHTS_QUEUE_KEY = "SIGNING_WEIGHTS_QUEUE"
SIGNED_MESSAGES_KEY = "SIGNED_MESSAGES"
DENDRITE_TYPE = "dendrite"
WEIGHTS_TYPE = "weights"

TYPE = "type"
MESSAGE = "message"
JOB_ID = "job_id"
IS_B64ENCODED = "is_b64encoded"

SIGNATURE = "signature"

SYNTHETIC_QUERY = "synthetic_query"
ORGANIC_QUERY = "organic_query"
JOB_RESULTS = "JOB_RESULTS"
