

# REDIS KEYS
SYNTHETIC_DATA_KEY = "SYNTHETIC_DATA"
SYNTHETIC_DATA_VERSIONS_KEY = "SYNTHETIC_DATA_VERSIONS"
SYNTHETIC_SCHEDULING_QUEUE_KEY = "SYNTHETIC_SCHEDULING_QUEUE"
QUERY_QUEUE_KEY = "QUERY_QUEUE"
HOTKEY_INFO_KEY = "HOTKEY_INFO"
CAPACITIES_KEY = "CAPACITIES"
PARTICIPANT_IDS_KEY = "PARTICIPANT_IDS"
PARITICIPANT_IDS_TO_STOP_KEY = "PARITICIPANT_IDS_TO_STOP"