services:
  client_node:
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
      POSTGRES_PORT: 5432
      POSTGRES_HOST: test_db
      POSTGRES_NAME: test_db
      ENV: test

  query_node:
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
      POSTGRES_PORT: 5432
      POSTGRES_HOST: test_db
      POSTGRES_NAME: test_db
      ENV: test
      NETUID: 19

  chain_node:
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
      POSTGRES_PORT: 5432
      POSTGRES_HOST: test_db
      POSTGRES_NAME: test_db
      RUN_ONCE: "true"
      DUMMY: "true"
      NETUID: 19
      ENV: test
      NETWORK: test
      SECONDS_BETWEEN_SYNC: 60

  control_center:
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
      POSTGRES_PORT: 5432
      POSTGRES_HOST: test_db
      POSTGRES_NAME: test_db
      ENV: test

  signing_service:
    environment:
      WALLET_NAME: test_wallet
      HOTKEY_NAME: test_hotkey
      ENV: test

  test_db:
    image: postgres:13
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    networks:
      - postgres_network
    container_name: 0_test_db

  dbmate:
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
      POSTGRES_PORT: 5432
      POSTGRES_HOST: test_db
      POSTGRES_NAME: test_db
