services:

  postgresql:
    ports:
      - "127.0.0.1:5432:5432"
    container_name: 0_postgresql_dev

  redis:
    ports:
      - "127.0.0.1:6379:6379"
    container_name: 0_redis_dev

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "127.0.0.1:8081:8081"
    networks:
      - redis_network
    depends_on:
      - redis
    container_name: 0_redis-commander

  adminer:
    image: adminer
    restart: always
    ports:
      - 5051:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgresql
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
    networks:
      - postgres_network
    depends_on:
      - postgresql
    container_name: 0_adminer

