version: "3"

tasks:
  control_node_dev:
    cmds:
      - ENV_FILE=.dev.env python -m validator.control_node.src.main
  
  query_node_dev:
    cmds: 
      - ENV_FILE=.dev.env python -m validator.query_node.src.main

  entry_node_dev:
    cmds:
      - uvicorn validator.entry_node.src.server:app --reload --host 0.0.0.0 --port 8091 --env-file .dev.env

  miners:
    cmds:
      - |
        uvicorn miner.server:app --reload --host 0.0.0.0 --port 4001 --env-file .1.env --log-level debug &
        uvicorn miner.server:app --reload --host 0.0.0.0 --port 4002 --env-file .2.env --log-level debug &
        wait
  dev_setup:
    cmds:
      - docker-compose --env-file .dev.env -f docker-compose.dev.yml up -d
      - docker kill dev_query_node dev_control_node
      - docker-compose --env-file .dev.env -f docker-compose.dev.yml -f docker-compose.utils.yml up -d