version: "3"

tasks:
  fetch_participants:
    cmds:
      - docker-compose exec -e ENV=test core_validator python validator/core/manage_participants/fetch_participants.py
  schedule_synthetics:
    cmds:
      - docker-compose exec -e ENV=test core_validator {{.CLI_ARGS}} python validator/core/manage_participants/scheduling_participants.py
  generate_synthetic_data:
    cmds:
      - docker-compose exec -e ENV=test core_validator python validator/core/store_synthetic_data/generate_synthetic_data.py
  run_query_node:
    cmds:
      - docker-compose exec -e ENV=test core_validator python validator/query_node/query_node.py
  metagraph_sync:
    cmds:
      - >
        docker-compose exec -e ENV=test -e RUN_ONCE=false {{.CLI_ARGS}} chain_node
        python validator/chain_node/sync_metagraph.py

  metagraph_sync_once:
    cmds:
      - docker-compose exec -e ENV=test  -e RUN_ONCE=true chain_node python validator/chain_node/sync_metagraph.py

  test_sign_dendrite_message:
    cmds:
      - docker-compose run --rm -e ENV=test -e RUN_ONCE=true signing_service  python validator/signing_service/dendrite.py
  test_keypair:
    cmds:
      - docker-compose exec -e ENV=test chain_node  python validator/chain_node/keypair.py
  test_weight_set:
    cmds:
      - docker-compose exec -e ENV=test chain_node  python validator/chain_node/set_weights.py
  dbmate-up:
    cmds:
      - docker-compose run --rm dbmate up
  dbmate-down:
    cmds:
      - docker-compose run --rm dbmate down
  dbmate-drop:
    cmds:
      - docker-compose run --rm dbmate drop
