version: "3"

tasks:

  set_weights:
    cmds:
      - docker compose --env-file .prod.env -f docker-compose.prod.yml run --entrypoint "python src/cycle/calculate_and_schedule_weights.py" control_node
  control_node_dev:
    cmds:
      - ENV_FILE=.dev.env python -m validator.control_node.src.main
  
  query_node_dev:
    cmds: 
      - ENV_FILE=.dev.env python -m validator.query_node.src.main

  entry_node_dev:
    cmds:
      - uvicorn validator.entry_node.src.server:app --reload --host 0.0.0.0 --port 8091 --env-file .dev.env

  dev_setup:
    cmds:
      - docker compose --env-file .dev.env -f docker-compose.dev.yml up -d
      - docker kill dev_query_node dev_control_node
      - docker compose --env-file .dev.env -f docker-compose.dev.yml -f docker-compose.utils.yml up -d

  miners_dev:
    cmds:
      - |
        uvicorn miner.server:app --reload --host 0.0.0.0 --port 4001 --env-file .1.env --log-level debug &
        uvicorn miner.server:app --reload --host 0.0.0.0 --port 4002 --env-file .2.env --log-level debug &
        wait
  
  createm:
    cmds:
      - |
        for env_file in .*.env; do
          if grep -q "NODE_PORT" "$env_file"; then
            node_port=$(grep "NODE_PORT" "$env_file" | cut -d '=' -f2)
            service_name="miner_$(echo $env_file | sed 's/\.//g' | sed 's/env//')"
            echo "Creating systemd service for $env_file with port $node_port"
            echo "[Unit]
        Description=Miner Service for $env_file
        After=network.target

        [Service]
        ExecStart=$(which uvicorn) miner.server:app --host 0.0.0.0 --port $node_port --env-file $(pwd)/$env_file --log-level debug
        WorkingDirectory=$(pwd)
        Restart=always
        User=$(whoami)

        [Install]
        WantedBy=multi-user.target" | sudo tee /etc/systemd/system/$service_name.service
            sudo systemctl daemon-reload
            sudo systemctl enable $service_name
            sudo systemctl start $service_name
          fi
        done

  stopm:
    cmds:
      - |
        for service in $(sudo systemctl list-units --type=service --state=active | grep miner_ | awk '{print $1}'); do
          echo "Stopping $service"
          sudo systemctl stop $service
        done

  restartm:
    cmds:
      - |
        for service in $(sudo systemctl list-units --type=service --state=active,failed | grep miner_ | awk '{print $1}'); do
          echo "Restarting $service"
          sudo systemctl restart $service
        done

  statusm:
    cmds:
      - |
        for service in $(sudo systemctl list-units --type=service --all | grep miner_ | grep '\.service' | awk '{print $1}' | grep -v '^●'); do
          echo "Status of $service:"
          sudo systemctl status $service --no-pager
          echo "----------------------"
        done
 