version: "3"

tasks:
  refresh_participants:
    cmds:
      - docker-compose run -e ENV=test -e NETUID=19 {{.CLI_ARGS}} control_center python validator/core/manage_participants/refresh_participants.py
  schedule_participants:
    cmds:
      - docker-compose run -e ENV=test -e NETUID=19  {{.CLI_ARGS}} --entrypoint python control_center validator/core/manage_participants/scheduling_participants.py
  generate_synthetic_data:
    cmds:
      - docker-compose exec -e ENV=test {{.CLI_ARGS}} control_center python validator/core/store_synthetic_data/generate_synthetic_data.py
  run_query_node:
    cmds:
      - docker-compose exec -e ENV=test -e NETUID=176  {{.CLI_ARGS}} control_center python validator/query_node/main.py
  metagraph_sync:
    cmds:
      - >
        docker-compose exec -e ENV=test -e RUN_ONCE=false {{.CLI_ARGS}} chain_node
        python validator/chain_node/sync_metagraph.py
  metagraph_sync_once:
    cmds:
      - docker-compose exec -e ENV=test  -e RUN_ONCE=true chain_node python validator/chain_node/sync_metagraph.py
  score_results:
    cmds:
      - docker-compose exec -e ENV=test  {{.CLI_ARGS}} chain_node python validator/core/get_rewards/main.py
  client_node:
    cmds:
      - docker-compose run {{.CLI_ARGS}} --entrypoint client_node python validator/client_node/main.py
  calculate_weights:
    cmds:
      - docker-compose run {{.CLI_ARGS}} --entrypoint python control_center  validator/core/calculate_weights/main.py

  test_chain_node_refresh_axons:
    cmds:
      - docker-compose -f docker-compose.yml -f docker-compose.testing.yml run --rm dbmate up
      - docker-compose -f docker-compose.yml -f docker-compose.testing.yml run --rm -e NEST_ASYNCIO=0 --entrypoint python chain_node /app/validator/chain_node/tests/test_refresh_axons.py
  test_chain_node_set_weights:
    cmds:
      - docker-compose -f docker-compose.yml -f docker-compose.testing.yml run --rm dbmate up
      - docker-compose -f docker-compose.yml -f docker-compose.testing.yml run --rm -e NEST_ASYNCIO=0 --entrypoint python chain_node /app/validator/chain_node/tests/test_set_weights.py
  test_control_center_schedule_synthetics:
    cmds:
      - docker-compose -f docker-compose.yml -f docker-compose.testing.yml run --rm dbmate up
      - docker-compose -f docker-compose.yml -f docker-compose.testing.yml run --rm  --entrypoint python control_center /app/validator/control_center/tests/test_schedule_synthetics.py
  test_sign_message:
    cmds:
      - docker-compose run --rm -e ENV=test -e RUN_ONCE=true signing_service  python validator/signing_service/main.py
  test_keypair:
    cmds:
      - docker-compose exec -e ENV=test chain_node  python validator/chain_node/keypair.py
  test_set_weights:
    cmds:
      - docker-compose exec -e ENV=test -e SUBTENSOR_NETWORK=test chain_node  python validator/chain_node/set_weights.py
  dbmate-up:
    cmds:
      - docker-compose run --rm dbmate up
  dbmate-down:
    cmds:
      - docker-compose run --rm dbmate down
  dbmate-drop:
    cmds:
      - docker-compose run --rm dbmate drop
