version: "3"

tasks:



  set_weights:
    cmds:
      - JUST_ONCE=true docker compose --env-file .vali.env -f docker-compose.yml run -e LOCALHOST=false --entrypoint "python src/set_weights/calculate_and_schedule_weights.py" weight_setter

  show_stats:
    cmds:
      - docker compose --env-file .vali.env -f docker-compose.yml run -e LOCALHOST=false --entrypoint "python src/collect_statistics.py" control_node

  control_node_dev:
    cmds:
      - LOCALHOST=true ENV_FILE=.vali.env python -m validator.control_node.src.main

  query_node_dev:
    cmds:
      - LOCALHOST=true ENV_FILE=.vali.env python -m validator.query_node.src.main

  entry_node_dev:
    cmds:
      - LOCALHOST=true uvicorn validator.entry_node.src.server:app --reload --host 0.0.0.0 --port 8090 --env-file .vali.env

  weight_setter_dev:
    cmds:
      - LOCALHOST=true ENV_FILE=.vali.env python -m validator.control_node.src.set_weights.calculate_and_schedule_weights

  dev_setup:
    cmds:
      - docker compose --env-file .vali.env -f docker-compose.yml -f docker-compose.dev.yml --profile entry_node_profile up -d --build --scale entry_node=0 --scale query_node=0 --scale control_node=0 --scale weight_setter=0
      # Now use control_node_dev etc

  m1_dev:
    cmds:
      - ENV=DEV uvicorn miner.server:app --reload --host 0.0.0.0 --port 4001 --env-file .1.env --log-level debug

  m2_dev:
    cmds:
      - ENV=DEV uvicorn miner.server:app --reload --host 0.0.0.0 --port 4002 --env-file .2.env --log-level debug

  update_docker_fiber_version:
    cmds:
      - docker run --rm nineteen-control_node sh -c "pip install git+https://github.com/rayonlabs/fiber.git@1.0.0 --upgrade"
      - docker run --rm nineteen-entry_node sh -c "pip install git+https://github.com/rayonlabs/fiber.git@1.0.0 --upgrade"
      - docker run --rm nineteen-query_node sh -c "pip install git+https://github.com/rayonlabs/fiber.git@1.0.0 --upgrade"

  createm:
    cmds:
      - bash start_miners.sh
