version: "3"

tasks:
  control_node_dev:
    cmds:
      - ENV_FILE=.dev.env python -m validator.control_node.src.main
  
  query_node_dev:
    cmds: 
      - ENV_FILE=.dev.env python -m validator.query_node.src.main