ORGANIC="organic"
SYNTHETIC="synthetic"
ACKNLOWEDGED="acknowledged"
ERROR="error"
STATUS_CODE="status_code"
ERROR_MESSAGE="error_message"
JOB_ID="job_id"
CONTENT="content"

MAX_ATTEMPTS_TO_CONFIRM_JOB_SUBMISSION = 3
MAX_ATTEMPTS_TO_COLLECT_RESULT = 3