SCORING_PERIOD_TIME = 60 * 60  # 0.5
VERSION_KEY = 1

BLOCKS_PER_EPOCH = 360


HOTKEY_PARAM = "HOTKEY_NAME"
WALLET_NAME_PARAM = "WALLET_NAME"
SUBTENSOR_NETWORK_PARAM = "SUBTENSOR_NETWORK"
SUBTENSOR_CHAINENDPOINT_PARAM = "SUBTENSOR_CHAINENDPOINT"
IS_VALIDATOR_PARAM = "IS_VALIDATOR"
API_SERVER_PORT_PARAM = "API_SERVER_PORT"
EXTERNAL_SERVER_ADDRESS_PARAM = "EXTERNAL_SERVER_ADDRESS"
AXON_PORT_PARAM = "AXON_PORT"
AXON_EXTERNAL_IP_PARAM = "AXON_EXTERNAL_IP"
  

VISION_DB = "vision_database.db"


