SCORING_PERIOD_TIME = 60 * 60  # 0.5


BLOCKS_PER_EPOCH = 360

DEFAULT_CFG_SCALE = 7
DEFAULT_HEIGHT = 1024
DEFAULT_WIDTH = 1024
DEFAULT_STEPS = 4

DEBUG_MINER_PARAM = "debug_miner"
CONFIG_FILEPATH = "config.yaml"

IS_VALIDATOR = "is_validator"


SINGULAR_GPU = "SINGULAR_GPU"

HOTKEY_PARAM = "HOTKEY_NAME"


IMAGE_WORKER_URL_PARAM = "IMAGE_WORKER_URL"
MIXTRAL_TEXT_WORKER_URL_PARAM = "MIXTRAL_TEXT_WORKER_URL"
LLAMA_3_TEXT_WORKER_URL_PARAM = "LLAMA_3_TEXT_WORKER_URL"


WALLET_NAME_PARAM = "WALLET_NAME"
SUBTENSOR_NETWORK_PARAM = "SUBTENSOR_NETWORK"
SUBTENSOR_CHAINENDPOINT_PARAM = "SUBTENSOR_CHAINENDPOINT"
IS_VALIDATOR_PARAM = "IS_VALIDATOR"
API_SERVER_PORT_PARAM = "API_SERVER_PORT"
EXTERNAL_SERVER_ADDRESS_PARAM = "EXTERNAL_SERVER_ADDRESS"
AXON_PORT_PARAM = "AXON_PORT"
AXON_EXTERNAL_IP_PARAM = "AXON_EXTERNAL_IP"


VISION_DB = "vision_database.db"
