

# REDIS KEYS
SYNTHETIC_DATA_KEY = "SYNTHETIC_DATA_KEY"
SYNTHETIC_QUERIES_TO_MAKE_KEY = "SYNTHETIC_QUERIES_TO_MAKE_KEY"
HOTKEY_INFO_KEY = "HOTKEY_INFO_KEY"
CAPACITIES_KEY = "CAPACITIES_KEY"
PARTICIPANT_IDS_KEY = "PARTICIPANT_IDS_KEY"