SIGNING_DENDRITE_QUEUE_KEY = "SIGNING_DENDRITE_QUEUE"
SIGNING_WEIGHTS_QUEUE_KEY = "SIGNING_WEIGHTS_QUEUE"
SIGNED_MESSAGES_KEY = "SIGNED_MESSAGES"
PUBLIC_KEYPAIR_INFO_KEY = "PUBLIC_KEYPAIR_INFO"
DENDRITE_TYPE = "dendrite"
WEIGHTS_TYPE = "weights"


MESSAGE = "message"
JOB_ID = "job_id"
IS_B64ENCODED = "is_b64encoded"

SIGNATURE = "signature"
